embed_assets: on
package_path: packages

javascripts:
  default:
    - public/javascripts/application.js
  admin:
    - public/javascripts/admin/jquery-1.4.js  
    - public/javascripts/admin/jquery-ui.js
    - public/javascripts/admin/jquery-tools.js
    - public/javascripts/admin/admin.js  
    - public/javascripts/admin/ui.js
    - public/javascripts/admin/ui.pagination.js
    - public/javascripts/admin/articles.js
stylesheets:
  default:
    - public/stylesheets/styles.css
  admin:
    - public/stylesheets/admin/styles.css
