embed_assets: on
package_path: packages

javascripts:
  default:
    - public/javascripts/application.js
  admin:
    - public/javascripts/admin/jquery-1.4.js  
    - public/javascripts/admin/jquery-ui.js
    - public/javascripts/admin/jquery-tools.js
    - public/javascripts/admin/jquery-rails.js
    - public/javascripts/admin/jquery-form.js
    - public/javascripts/admin/jquery-googlemaps.js
    - public/javascripts/admin/jquery-treeview.js
    - public/javascripts/admin/jquery-prettyphoto.js
    - public/javascripts/admin/jquery-jcrop.js
    - public/javascripts/tiny_mce/jquery.tinymce.js
    - public/javascripts/admin/admin.js  
    - public/javascripts/admin/ui.js
    - public/javascripts/admin/ui.pagination.js
    - public/javascripts/admin/articles.js
    - public/javascripts/admin/venues.js
    - public/javascripts/admin/tagging.js
    - public/javascripts/admin/tinymce.js
    - public/javascripts/admin/asset_manager.js
stylesheets:
  default:
    - public/stylesheets/styles.css
  admin:
    - public/stylesheets/admin/styles.css
  show_article:
    - public/stylesheets/admin/show_article.css
  print_article:
    - public/stylesheets/admin/print_article.css
